version: '3.7'
 
services:
  web:
    build: ./web
    image:  mydjango307
    container_name: mydjango307
    command: >
      bash -c 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./web/app/:/usr/src/app/
    ports:
      - 8000:8000
